### ISSUE TITLE
Path PB

### ISSUE THREAD

**Issue by hedjour** [BIOP/ijp-atlas#3]
When I run Abba on Ubuntu 22.04.2LTs I get this error :
```java
ch.systemsx.cisd.hdf5.exceptions.HDF5FileNotFoundException: Path does not exit. (/home/user/cached_atlas/WHS_SD_rat_atlas_v4_b.xml/..\WHS_SD_rat_atlas_v4.h5)
```
This is the good path : /home/user/cached_atlas/WHS_SD_rat_atlas_v4_b.xml/..\WHS_SD_rat_atlas_v4.h5

It looks like the path switch between Unix system and Windows system. 
Is it possible to put the Atlas in a fiji or QuPath extension directory ? to avoid this problem.

**Comment by NicoKiaru** [comment]
If you put a file named `ABBA_Atlas_folder.txt` in the folder `Fiji.app\plugins\BIOP` that contains just a file path, it should be picked up by ABBA. But I'm not completely sure that that is the problem.
[ABBA_Atlas_folder.txt](https://github.com/BIOP/ijp-atlas/files/11077726/ABBA_Atlas_folder.txt)

Just try first to open the xml file in BigDataViewer like this:
![open_atlas](https://user-images.githubusercontent.com/20223054/227920261-b3cfefb8-0ba5-4e67-8bbf-4911ee8d553e.gif)

If it fails at this point, then it's an issue with the HDF5 java library. There's someone actively working on it at the moment, I'll contact him

**Comment by NicoKiaru** [comment]
Another potential patch:

In the xml file of the atlas, there are these 3 lines:

```
<ImageLoader format="bdv.hdf5">
      <hdf5 type="relative">ccf2017-mod65000-border-centered-mm-bc.h5</hdf5>
</ImageLoader>
```
Could you try to tweak these with an absolute path ?

```
<ImageLoader format="bdv.hdf5">
      <hdf5 type="absolute">The_full_path_to ccf2017-mod65000-border-centered-mm-bc.h5</hdf5>
</ImageLoader>
```
ping @tpietzsch, @mkitti (but I still need a minimally self contained example...)

**Comment by hedjour** [comment]
Thanks I can open the atlas image.
But when I run the Abba plugin I get : with absolute path in cached_atlas directory and it's work a litle more to : 
```java
 ImageJ2
 'ba' is required but unset.
```
And in the console I can read :
```java
[INFO] Reading available sites from https://imagej.net/
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw error
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ch.epfl.biop.atlas.aligner.command.ABBAOpenAtlasCommand.run(ABBAOpenAtlasCommand.java:34)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Module threw error
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:130)
	... 6 more
Caused by: java.lang.NoSuchMethodError: spimdata.util.Displaysettings.applyDisplaysettings(Lbdv/viewer/SourceAndConverter;Lspimdata/util/Displaysettings;)V
	at spimdata.util.DisplaysettingsHandler.loadEntity(DisplaysettingsHandler.java:42)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.lambda$register$3(SourceAndConverterService.java:477)
	at java.util.HashMap$KeySet.forEach(HashMap.java:934)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.register(SourceAndConverterService.java:474)
	at sc.fiji.bdvpg.spimdata.importer.SpimDataFromXmlImporter.apply(SpimDataFromXmlImporter.java:76)
	at sc.fiji.bdvpg.spimdata.importer.SpimDataFromXmlImporter.get(SpimDataFromXmlImporter.java:68)
	at ch.epfl.biop.atlas.rat.waxholm.spraguedawley.v4.WaxholmSpragueDawleyRatV4Map.initialize(WaxholmSpragueDawleyRatV4Map.java:81)
	at ch.epfl.biop.atlas.rat.waxholm.spraguedawley.v4.WaxholmSpragueDawleyRatV4Atlas.initialize(WaxholmSpragueDawleyRatV4Atlas.java:56)
	at ch.epfl.biop.atlas.rat.waxholm.spraguedawley.v4.command.WaxholmSpragueDawleyRatV4Command.run(WaxholmSpragueDawleyRatV4Command.java:67)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ch.epfl.biop.atlas.aligner.gui.bdv.ABBABdvStartCommand.initialize(ABBABdvStartCommand.java:67)
	at org.scijava.module.AbstractModule.initialize(AbstractModule.java:80)
	at org.scijava.module.process.InitPreprocessor.process(InitPreprocessor.java:59)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:102)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:152)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	... 6 more
Caused by: java.lang.NullPointerException
	at org.scijava.object.ObjectIndex.getType(ObjectIndex.java:274)
	at org.scijava.object.ObjectIndex.add(ObjectIndex.java:269)
	at org.scijava.object.ObjectIndex.add(ObjectIndex.java:191)
	at org.scijava.object.NamedObjectIndex.add(NamedObjectIndex.java:50)
	at org.scijava.object.ObjectService.addObject(ObjectService.java:91)
	at org.scijava.object.ObjectService.addObject(ObjectService.java:86)
	at ch.epfl.biop.atlas.struct.AtlasProcessorPlugin.lambda$process$0(AtlasProcessorPlugin.java:61)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
	at ch.epfl.biop.atlas.struct.AtlasProcessorPlugin.process(AtlasProcessorPlugin.java:56)
	at org.scijava.module.ModuleRunner.postProcess(ModuleRunner.java:114)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:172)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
Keymap list file /home/user/.config/bigdataviewer/keymaps/keymaps.yaml not found. Using builtin styles.
[WARNING] 4 exceptions occurred during plugin discovery.
Appearance settings file /home/user/.config/bigdataviewer/appearance.yaml not found. Using defaults.
java.lang.NullPointerException
	at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView.<init>(BdvMultislicePositionerView.java:648)
	at ch.epfl.biop.atlas.aligner.gui.bdv.ABBABdvStartCommand.run(ABBABdvStartCommand.java:52)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Keymap list file /home/user/.config/bigdataviewer/keymaps/keymaps.yaml not found. Using builtin styles.
[WARNING] 4 exceptions occurred during plugin discovery.
Appearance settings file /home/user/.config/bigdataviewer/appearance.yaml not found. Using defaults.

```

**Comment by hedjour** [comment]
Any Idea what is 'Ba' ? except egyptian mythologie

**Comment by NicoKiaru** [comment]
Where can I find your email @hedjour ? Would you have time for a quick zoom meeting ? You can find my email here: https://www.epfl.ch/research/facilities/ptbiop/staff/

**Comment by hedjour** [comment]
@NicoKiaru I sent you an email directly

**Comment by NicoKiaru** [comment]
We're struggling again with this issue with @romainGuiet on linux (the one with java.lang.NoSuchMethodError: spimdata.util.Displaysettings.applyDisplaysettings ).

**Comment by NicoKiaru** [comment]
I need to test on linux - probably through WSL
